MAKE[0]="'make' all DKMS_KERNEL_VERSION=$kernelver"
CLEAN="'make' clean"
BUILT_MODULE_NAME[0]="applesmc"
BUILT_MODULE_LOCATION[0]=''
PACKAGE_NAME="applesmc"
PACKAGE_VERSION="0.1"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"
AUTOINSTALL="yes"
REMAKE_INITRD=no
